---
# configuration file for my app
# where is the dataset and what's its name? 
  dataset:
    filename: 'vehicles_us.csv'
    path: 'data/'
# where are the jupyter notebooks?
  notebooks:
    path: 'notebooks/'
# where are the project's support modules?
  utils:
    path: 'utils/'
